---
# tasks file for ansible-role-cd-hit-3.1.1

- name: "Download cd-hit-3.1.1"
  get_url:
    url: http://www.bioinformatics.org/download/cd-hit/cd-hit-2007-0131.tar.gz
    dest: "{{ ansible_env.PWD }}/software/cd-hit-2007-0131.tar.gz"

- name: "Unarchive cd-hit-3.1.1"
  unarchive:
    src: "{{ ansible_env.PWD }}/software/cd-hit-2007-0131.tar.gz"
    dest: "{{ ansible_env.PWD }}/software/"
    remote_src: yes

- name: "Execute Makefile"
  command: make -C {{ ansible_env.PWD }}/software/cd-hit
  
- name: Add cd-hit to .bashrc
  shell: echo export PATH={{ ansible_env.PWD }}/software/cd-hit:$PATH >> {{ ansible_env.PWD }}/.bashrc
