---

- name: Clone ea-utils git repo
  git: 
    repo: 'https://github.com/ExpressionAnalysis/ea-utils.git'
    dest: "{{ ansible_env.PWD }}/software/ea-utils"

- name: Add path to .bashrc
  shell: echo export PATH={{ ansible_env.PWD }}/software/ea-utils/clipper:$PATH >> {{ ansible_env.PWD }}/.bashrc
