---

- name: "Ensure software folder exists"
  file: path={{ ansible_env.PWD }}/software/bin state=directory mode=0777

- name: "Download and decompress rdp classifier"
  unarchive:
    src: https://downloads.sourceforge.net/project/rdp-classifier/rdp-classifier/rdp_classifier_2.2.zip
    dest: "{{ ansible_env.PWD }}/software/bin"
    remote_src: True

- name: "Downlaod and unarchive cdbfasta"
  unarchive:
    src: ftp://occams.dfci.harvard.edu/pub/bio/tgi/software/cdbfasta/cdbfasta.tar.gz
    dest: "{{ ansible_env.PWD }}/software/bin"
    remote_src: True

- name: "Execute Makefile"
  command: make -C {{ ansible_env.PWD }}/software/bin/cdbfasta

# - name: "Add cdbfasta to .bashrc"
#   shell: echo export PATH={{ ansible_env.PWD }}/software/cdbfasta:$PATH >> {{ ansible_env.PWD }}/.bashrc
#
# - name: "Download Cytoscape startup script"
#   get_url:
#     url: http://chianti.ucsd.edu/cytoscape-3.5.1/Cytoscape_3_5_1_unix.sh
#     dest: "{{ ansible_env.PWD }}/software/Cytoscape_3_5_1_unix.sh"
#
# - name: "Execute Cytoscape setup script without GUI"
#   command: sh {{ ansible_env.PWD }}/software/Cytoscape_3_5_1_unix.sh -q
#
# - name: Download sourcetracker
#   get_url:
#     url: https://downloads.sourceforge.net/project/sourcetracker/sourcetracker-0.9.8.tar.gz
#     dest: "{{ ansible_env.PWD }}/software/sourcetracker-0.9.8.tar.gz"
#
# - name: Decompress download
#   unarchive:
#     src: "{{ ansible_env.PWD }}/software/sourcetracker-0.9.8.tar.gz"
#     dest: "{{ ansible_env.PWD }}/software/"
#     remote_src: True
#
# - name: Add sourcetracker to .bashrc
#   shell: echo export SOURCETRACKER_PATH={{ ansible_env.PWD }}/software/sourcetracker-0.9.8/src >> {{ ansible_env.PWD }}/.bashrc
#
# - include: redhat-main.yml
#   when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
#
# - include: debian-main.yml
#   when: ansible_os_family == "Debian"
#

