---
# tasks file for ansible-role-sumaclust

- name: "Download Sumaclust"
  get_url:
    url: ftp://ftp.microbio.me/pub/QIIME-v1.9.0-dependencies/suma_package_V_1.0.00.tar.gz
    dest: "{{ ansible_env.PWD }}/software/suma_package_V_1.0.00.tar.gz"

- name: "Unarchive Downlaod"
  unarchive:
    src: "{{ ansible_env.PWD }}/software/suma_package_V_1.0.00.tar.gz"
    dest: "{{ ansible_env.PWD }}/software"
    remote_src: True
    copy: no

- name: Execute sumaclust Makefile
  command: make -C {{ ansible_env.PWD }}/software/suma_package_V_1.0.00/sumaclust

- name: "Execute sumatra Makefile"
  command: make -C {{ ansible_env.PWD }}/software/suma_package_V_1.0.00/sumatra

- name: Add sumaclust and sumatra to .bashrc
  shell: echo export PATH={{ ansible_env.PWD }}/software/suma_package_V_1.0.00/sumaclust:{{ ansible_env.PWD }}/software/suma_package_V_1.0.00/sumatra:$PATH >> {{ ansible_env.PWD }}/.bashrc
